//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebPPT.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class arCreditos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public arCreditos()
        {
            this.arCreditosDetalle = new HashSet<arCreditosDetalle>();
        }
    
        public int NoCredito { get; set; }
        public System.DateTime Fecha { get; set; }
        public string IdCliente { get; set; }
        public string Cliente { get; set; }
        public string IdTipoNotaCredito { get; set; }
        public string Concepto { get; set; }
        public decimal Monto { get; set; }
        public string ModuloOrigen { get; set; }
        public string Referencia { get; set; }
        public string Notas { get; set; }
        public System.DateTime FechaCreado { get; set; }
        public string IdUsuario { get; set; }
        public string cStatus { get; set; }
        public bool Posteado { get; set; }
        public Nullable<int> IdCAI { get; set; }
        public string NoCreditoFiscal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arCreditosDetalle> arCreditosDetalle { get; set; }
        public virtual arNotaCreditoTipo arNotaCreditoTipo { get; set; }
    }
}
