//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebPPT.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class arFacturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public arFacturas()
        {
            this.arFacturasDescuento = new HashSet<arFacturasDescuento>();
            this.arFacturasDetalle = new HashSet<arFacturasDetalle>();
            this.arFacturasTax = new HashSet<arFacturasTax>();
        }
    
        public string NoFactura { get; set; }
        public string IdCliente { get; set; }
        public string Cliente { get; set; }
        public string IdTerminoCredito { get; set; }
        public string IdAlmacen { get; set; }
        public string IdVendedor { get; set; }
        public int NoTurno { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Descuentos { get; set; }
        public decimal Impuestos { get; set; }
        public decimal Total { get; set; }
        public decimal Pagos { get; set; }
        public decimal Creditos { get; set; }
        public decimal Saldo { get; set; }
        public string ModuloOrigen { get; set; }
        public string Notas { get; set; }
        public System.DateTime FechaCreado { get; set; }
        public string IdUsuario { get; set; }
        public string cStatus { get; set; }
        public bool Posteado { get; set; }
        public Nullable<int> IdCAI { get; set; }
        public string NoFacturaFiscal { get; set; }
        public bool OrdComExenta { get; set; }
        public string NoOrdComExe { get; set; }
        public string NoConRegExo { get; set; }
        public string NoRegSag { get; set; }
        public string NoFacProforma { get; set; }
        public decimal ImporteExonerado { get; set; }
        public decimal ImporteExento { get; set; }
    
        public virtual arClientes arClientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arFacturasDescuento> arFacturasDescuento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arFacturasDetalle> arFacturasDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arFacturasTax> arFacturasTax { get; set; }
        public virtual arTerminoCredito arTerminoCredito { get; set; }
        public virtual icAlmacenes icAlmacenes { get; set; }
        public virtual posTurnos posTurnos { get; set; }
        public virtual posVendedores posVendedores { get; set; }
    }
}
