//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebPPT.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class bnBancos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bnBancos()
        {
            this.arMetodoPago = new HashSet<arMetodoPago>();
        }
    
        public string IdBanco { get; set; }
        public string Descripcion { get; set; }
        public string IdMoneda { get; set; }
        public string ABA { get; set; }
        public string NoCuenta { get; set; }
        public string IdCuenta { get; set; }
        public bool EmiteCk { get; set; }
        public int UltimoCk { get; set; }
        public bool lStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arMetodoPago> arMetodoPago { get; set; }
        public virtual bnMonedas bnMonedas { get; set; }
        public virtual glCuentas glCuentas { get; set; }
    }
}
