//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebPPT.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class gcPrestamos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gcPrestamos()
        {
            this.gcOrdenPago = new HashSet<gcOrdenPago>();
            this.gcPrestamosAmor = new HashSet<gcPrestamosAmor>();
            this.gcPrestamosAmorMov = new HashSet<gcPrestamosAmorMov>();
            this.gcPrestamosAmorMovDet = new HashSet<gcPrestamosAmorMovDet>();
            this.gcPrestamosAvales = new HashSet<gcPrestamosAvales>();
            this.gcPrestamosDoc = new HashSet<gcPrestamosDoc>();
            this.gcPrestamosGar = new HashSet<gcPrestamosGar>();
            this.gcPrestamosRefCom = new HashSet<gcPrestamosRefCom>();
            this.gcPrestamosRefFin = new HashSet<gcPrestamosRefFin>();
            this.gcPrestamosRefPer = new HashSet<gcPrestamosRefPer>();
            this.gcPrestamosReq = new HashSet<gcPrestamosReq>();
        }
    
        public int NoPrestamo { get; set; }
        public string IdTipoPrestamo { get; set; }
        public string IdCliente { get; set; }
        public string Cliente { get; set; }
        public string TipoCalculo { get; set; }
        public bool CalcularMora { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaOtorgado { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<decimal> TasaIntAnual { get; set; }
        public Nullable<decimal> TasaIntMensual { get; set; }
        public Nullable<decimal> IntMoraAnual { get; set; }
        public Nullable<decimal> IntMoraMensual { get; set; }
        public Nullable<decimal> PlazoAnios { get; set; }
        public Nullable<decimal> PlazoMeses { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> Intereses { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string IdUsuarioCreado { get; set; }
        public string IdUsuarioProceso { get; set; }
        public string Referencia { get; set; }
        public string Notas { get; set; }
        public System.DateTime FechaCreado { get; set; }
        public string cStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gcOrdenPago> gcOrdenPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gcPrestamosAmor> gcPrestamosAmor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gcPrestamosAmorMov> gcPrestamosAmorMov { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gcPrestamosAmorMovDet> gcPrestamosAmorMovDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gcPrestamosAvales> gcPrestamosAvales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gcPrestamosDoc> gcPrestamosDoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gcPrestamosGar> gcPrestamosGar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gcPrestamosRefCom> gcPrestamosRefCom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gcPrestamosRefFin> gcPrestamosRefFin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gcPrestamosRefPer> gcPrestamosRefPer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gcPrestamosReq> gcPrestamosReq { get; set; }
    }
}
