//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebPPT.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class glCuentas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public glCuentas()
        {
            this.apProveedores = new HashSet<apProveedores>();
            this.apProveedoresTipo = new HashSet<apProveedoresTipo>();
            this.apProveedoresTipo1 = new HashSet<apProveedoresTipo>();
            this.apProveedoresTipo2 = new HashSet<apProveedoresTipo>();
            this.arClientes = new HashSet<arClientes>();
            this.arClientesTipo = new HashSet<arClientesTipo>();
            this.arDescuentos = new HashSet<arDescuentos>();
            this.arMetodoPago = new HashSet<arMetodoPago>();
            this.arNotaCreditoTipo = new HashSet<arNotaCreditoTipo>();
            this.arNotaDebitoTipo = new HashSet<arNotaDebitoTipo>();
            this.bnBancos = new HashSet<bnBancos>();
            this.SysTaxes = new HashSet<SysTaxes>();
            this.SysTaxes1 = new HashSet<SysTaxes>();
            this.icAjusteClase = new HashSet<icAjusteClase>();
            this.icAlmacenes = new HashSet<icAlmacenes>();
            this.icTipoInventarioCtasCostos = new HashSet<icTipoInventarioCtasCostos>();
            this.icTipoInventarioCtasIngresos = new HashSet<icTipoInventarioCtasIngresos>();
            this.icDeptos1 = new HashSet<icDeptos>();
            this.icDeptos2 = new HashSet<icDeptos>();
        }
    
        public string IdCuenta { get; set; }
        public string Descripcion { get; set; }
        public int IdCategoria { get; set; }
        public string Tipo { get; set; }
        public string CreditoDebito { get; set; }
        public string IdGrupo { get; set; }
        public string IdSubGrupo { get; set; }
        public string IdDepto { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<apProveedores> apProveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<apProveedoresTipo> apProveedoresTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<apProveedoresTipo> apProveedoresTipo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<apProveedoresTipo> apProveedoresTipo2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arClientes> arClientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arClientesTipo> arClientesTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arDescuentos> arDescuentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arMetodoPago> arMetodoPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arNotaCreditoTipo> arNotaCreditoTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arNotaDebitoTipo> arNotaDebitoTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bnBancos> bnBancos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysTaxes> SysTaxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysTaxes> SysTaxes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icAjusteClase> icAjusteClase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icAlmacenes> icAlmacenes { get; set; }
        public virtual glCuentasCategoria glCuentasCategoria { get; set; }
        public virtual glCuentasGrupo glCuentasGrupo { get; set; }
        public virtual glCuentasSubGrupo glCuentasSubGrupo { get; set; }
        public virtual icDeptos icDeptos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icTipoInventarioCtasCostos> icTipoInventarioCtasCostos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icTipoInventarioCtasIngresos> icTipoInventarioCtasIngresos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icDeptos> icDeptos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icDeptos> icDeptos2 { get; set; }
    }
}
