//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebPPT.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class icBines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public icBines()
        {
            this.icInventarioFisicoDetalle = new HashSet<icInventarioFisicoDetalle>();
            this.icProductosInventario = new HashSet<icProductosInventario>();
            this.icRecepcionesDetalle = new HashSet<icRecepcionesDetalle>();
            this.icRequisicionesSalidaDetalle = new HashSet<icRequisicionesSalidaDetalle>();
            this.icRequisicionesTransfDetalle = new HashSet<icRequisicionesTransfDetalle>();
            this.icRequisicionesTransfDetalle1 = new HashSet<icRequisicionesTransfDetalle>();
        }
    
        public string IdBin { get; set; }
        public string IdAlmacen { get; set; }
        public string Descripcion { get; set; }
        public bool lStatus { get; set; }
    
        public virtual icAlmacenes icAlmacenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icInventarioFisicoDetalle> icInventarioFisicoDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icProductosInventario> icProductosInventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icRecepcionesDetalle> icRecepcionesDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icRequisicionesSalidaDetalle> icRequisicionesSalidaDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icRequisicionesTransfDetalle> icRequisicionesTransfDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icRequisicionesTransfDetalle> icRequisicionesTransfDetalle1 { get; set; }
    }
}
