//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebPPT.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class icTipoInventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public icTipoInventario()
        {
            this.icProductos = new HashSet<icProductos>();
            this.icTipoInventarioCtasCostos = new HashSet<icTipoInventarioCtasCostos>();
            this.icTipoInventarioCtasIngresos = new HashSet<icTipoInventarioCtasIngresos>();
        }
    
        public string IdTipoInventario { get; set; }
        public string Descripcion { get; set; }
        public bool lStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icProductos> icProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icTipoInventarioCtasCostos> icTipoInventarioCtasCostos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icTipoInventarioCtasIngresos> icTipoInventarioCtasIngresos { get; set; }
    }
}
