//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebPPT.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class posCategorias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public posCategorias()
        {
            this.posCategoriasModi = new HashSet<posCategoriasModi>();
            this.posCategoriasProductos = new HashSet<posCategoriasProductos>();
        }
    
        public string IdCategoria { get; set; }
        public string Descripcion { get; set; }
        public string LabelBoton { get; set; }
        public Nullable<decimal> FontSize { get; set; }
        public Nullable<int> NoBoton { get; set; }
        public bool lStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<posCategoriasModi> posCategoriasModi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<posCategoriasProductos> posCategoriasProductos { get; set; }
    }
}
