//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebPPT.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class posTurnos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public posTurnos()
        {
            this.arFacturas = new HashSet<arFacturas>();
        }
    
        public int NoTurno { get; set; }
        public string IdTurno { get; set; }
        public string IdAlmacen { get; set; }
        public string IdUsuario { get; set; }
        public string IdTerminal { get; set; }
        public decimal FondoDeCaja { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaCreado { get; set; }
        public string cStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arFacturas> arFacturas { get; set; }
        public virtual icAlmacenes icAlmacenes { get; set; }
        public virtual posTurnosTabla posTurnosTabla { get; set; }
    }
}
