//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWebPPT.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysTaxes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SysTaxes()
        {
            this.arFacturasDetalle = new HashSet<arFacturasDetalle>();
            this.arServicios = new HashSet<arServicios>();
            this.icProductos = new HashSet<icProductos>();
            this.icRecepcionesDetalle = new HashSet<icRecepcionesDetalle>();
        }
    
        public string IdTax { get; set; }
        public string Descripcion { get; set; }
        public decimal Valor { get; set; }
        public string IdCuentaAR { get; set; }
        public string IdCuentaAP { get; set; }
        public bool ImprimirEnFactura { get; set; }
        public bool lStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arFacturasDetalle> arFacturasDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arServicios> arServicios { get; set; }
        public virtual glCuentas glCuentas { get; set; }
        public virtual glCuentas glCuentas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icProductos> icProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icRecepcionesDetalle> icRecepcionesDetalle { get; set; }
    }
}
